name: Deploy SQL
on:
  push:
    branches:
      - main
      - FM-18
    paths:
      - "./sql/**"
jobs:
  deploy-digital-ocean:
    runs-on: ubuntu-latest
    environment: staging
    env:
      host: ${{ secrets.DO_DB_HOST }}
      port: ${{ secrets.DO_DB_PORT }}
      secret: ${{ secrets.DO_DB_SECRET }}
      user: ${{ secrets.DO_DB_USER }}
      database: ${{ secrets.DO_DB_NAME }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Show databases
        run: mysql -u $user -p${secret} -h $host -P $port --execute="show databases;"
      - name: Drop database
        run: mysql -u $user -p${secret} -h $host -P $port --execute="DROP DATABASE IF EXISTS $database;"
      - name: Show databases
        run: mysql -u $user -p${secret} -h $host -P $port --execute="show databases;"
      - name: Create and populate database
        run: cat ./sql/*.sql | mysql -u $user -p${secret} -h $host -P $port
      - name: Test that view object exists
        run: mysql -u $user -p${secret} -h $host -P $port --database="${database}" --execute="select * from students_program;"
